"""Built-in stock presets matching HandBrake official presets."""

STOCK_PRESETS = [
    ('-- General --', None),
    ('Very Fast 2160p60 4K HEVC', {
        'video_codec':'H.265', 'quality':26, 'sw_preset':'superfast',
        'hw_preset':'p1', 'amf_quality':'speed', 'qsv_preset':'veryfast',
        'resolution':'4K (3840x2160)', 'aspect_ratio':'Source',
        'anamorphic':False, 'deinterlace':'None',
        'use_nvenc':False, 'use_qsv':False, 'use_amf':False,
        'sub_track':'None', 'sub_burn':False,
        'two_pass':False, 'target_bitrate':'7500k',
        'use_crop':False, 'crop_values':'', 'keep_chapters':True,
    }),
    ('Very Fast 1080p30', {
        'video_codec':'H.264', 'quality':24, 'sw_preset':'veryfast',
        'hw_preset':'p1', 'amf_quality':'speed', 'qsv_preset':'veryfast',
        'resolution':'1080p (1920x1080)', 'aspect_ratio':'Source',
        'anamorphic':False, 'deinterlace':'None',
        'use_nvenc':False, 'use_qsv':False, 'use_amf':False,
        'sub_track':'None', 'sub_burn':False,
        'two_pass':False, 'target_bitrate':'4000k',
        'use_crop':False, 'crop_values':'', 'keep_chapters':True,
    }),
    ('Very Fast 720p30', {
        'video_codec':'H.264', 'quality':23, 'sw_preset':'veryfast',
        'hw_preset':'p1', 'amf_quality':'speed', 'qsv_preset':'veryfast',
        'resolution':'720p (1280x720)', 'aspect_ratio':'Source',
        'anamorphic':False, 'deinterlace':'None',
        'use_nvenc':False, 'use_qsv':False, 'use_amf':False,
        'sub_track':'None', 'sub_burn':False,
        'two_pass':False, 'target_bitrate':'2000k',
        'use_crop':False, 'crop_values':'', 'keep_chapters':True,
    }),
    ('Very Fast 480p30', {
        'video_codec':'H.264', 'quality':22, 'sw_preset':'veryfast',
        'hw_preset':'p1', 'amf_quality':'speed', 'qsv_preset':'veryfast',
        'resolution':'480p (854x480)', 'aspect_ratio':'Source',
        'anamorphic':False, 'deinterlace':'None',
        'use_nvenc':False, 'use_qsv':False, 'use_amf':False,
        'sub_track':'None', 'sub_burn':False,
        'two_pass':False, 'target_bitrate':'1000k',
        'use_crop':False, 'crop_values':'', 'keep_chapters':True,
    }),
    ('Fast 2160p60 4K HEVC', {
        'video_codec':'H.265', 'quality':24, 'sw_preset':'faster',
        'hw_preset':'p2', 'amf_quality':'balanced', 'qsv_preset':'faster',
        'resolution':'4K (3840x2160)', 'aspect_ratio':'Source',
        'anamorphic':False, 'deinterlace':'None',
        'use_nvenc':False, 'use_qsv':False, 'use_amf':False,
        'sub_track':'None', 'sub_burn':False,
        'two_pass':False, 'target_bitrate':'13000k',
        'use_crop':False, 'crop_values':'', 'keep_chapters':True,
    }),
    ('Fast 1080p30', {
        'video_codec':'H.264', 'quality':22, 'sw_preset':'fast',
        'hw_preset':'p4', 'amf_quality':'balanced', 'qsv_preset':'fast',
        'resolution':'1080p (1920x1080)', 'aspect_ratio':'Source',
        'anamorphic':False, 'deinterlace':'None',
        'use_nvenc':False, 'use_qsv':False, 'use_amf':False,
        'sub_track':'None', 'sub_burn':False,
        'two_pass':False, 'target_bitrate':'6000k',
        'use_crop':False, 'crop_values':'', 'keep_chapters':True,
    }),
    ('HQ 2160p60 4K HEVC Surround', {
        'video_codec':'H.265', 'quality':22, 'sw_preset':'medium',
        'hw_preset':'p3', 'amf_quality':'quality', 'qsv_preset':'medium',
        'resolution':'4K (3840x2160)', 'aspect_ratio':'Source',
        'anamorphic':False, 'deinterlace':'None',
        'use_nvenc':False, 'use_qsv':False, 'use_amf':False,
        'sub_track':'None', 'sub_burn':False,
        'two_pass':False, 'target_bitrate':'16000k',
        'use_crop':False, 'crop_values':'', 'keep_chapters':True,
    }),
    ('HQ 1080p30 Surround', {
        'video_codec':'H.264', 'quality':20, 'sw_preset':'slow',
        'hw_preset':'p3', 'amf_quality':'quality', 'qsv_preset':'slow',
        'resolution':'1080p (1920x1080)', 'aspect_ratio':'Source',
        'anamorphic':False, 'deinterlace':'None',
        'use_nvenc':False, 'use_qsv':False, 'use_amf':False,
        'sub_track':'None', 'sub_burn':False,
        'two_pass':False, 'target_bitrate':'8000k',
        'use_crop':False, 'crop_values':'', 'keep_chapters':True,
    }),
    ('Super HQ 2160p60 4K HEVC Surround', {
        'video_codec':'H.265', 'quality':20, 'sw_preset':'veryslow',
        'hw_preset':'p1', 'amf_quality':'quality', 'qsv_preset':'veryslow',
        'resolution':'4K (3840x2160)', 'aspect_ratio':'Source',
        'anamorphic':False, 'deinterlace':'None',
        'use_nvenc':False, 'use_qsv':False, 'use_amf':False,
        'sub_track':'None', 'sub_burn':False,
        'two_pass':False, 'target_bitrate':'20000k',
        'use_crop':False, 'crop_values':'', 'keep_chapters':True,
    }),
    ('Super HQ 1080p30 Surround', {
        'video_codec':'H.264', 'quality':18, 'sw_preset':'veryslow',
        'hw_preset':'p1', 'amf_quality':'quality', 'qsv_preset':'veryslow',
        'resolution':'1080p (1920x1080)', 'aspect_ratio':'Source',
        'anamorphic':False, 'deinterlace':'None',
        'use_nvenc':False, 'use_qsv':False, 'use_amf':False,
        'sub_track':'None', 'sub_burn':False,
        'two_pass':False, 'target_bitrate':'10000k',
        'use_crop':False, 'crop_values':'', 'keep_chapters':True,
    }),
    ('-- Matroska --', None),
    ('H.265 MKV 2160p60 4K', {
        'video_codec':'H.265', 'quality':24, 'sw_preset':'slow',
        'hw_preset':'p2', 'amf_quality':'quality', 'qsv_preset':'slow',
        'resolution':'4K (3840x2160)', 'aspect_ratio':'Source',
        'anamorphic':False, 'deinterlace':'None',
        'use_nvenc':False, 'use_qsv':False, 'use_amf':False,
        'sub_track':'None', 'sub_burn':False,
        'two_pass':False, 'target_bitrate':'13000k',
        'use_crop':False, 'crop_values':'', 'keep_chapters':True,
    }),
    ('H.265 MKV 1080p30', {
        'video_codec':'H.265', 'quality':22, 'sw_preset':'slow',
        'hw_preset':'p3', 'amf_quality':'quality', 'qsv_preset':'slow',
        'resolution':'1080p (1920x1080)', 'aspect_ratio':'Source',
        'anamorphic':False, 'deinterlace':'None',
        'use_nvenc':False, 'use_qsv':False, 'use_amf':False,
        'sub_track':'None', 'sub_burn':False,
        'two_pass':False, 'target_bitrate':'6000k',
        'use_crop':False, 'crop_values':'', 'keep_chapters':True,
    }),
    ('H.264 MKV 1080p30', {
        'video_codec':'H.264', 'quality':22, 'sw_preset':'medium',
        'hw_preset':'p4', 'amf_quality':'balanced', 'qsv_preset':'medium',
        'resolution':'1080p (1920x1080)', 'aspect_ratio':'Source',
        'anamorphic':False, 'deinterlace':'None',
        'use_nvenc':False, 'use_qsv':False, 'use_amf':False,
        'sub_track':'None', 'sub_burn':False,
        'two_pass':False, 'target_bitrate':'6000k',
        'use_crop':False, 'crop_values':'', 'keep_chapters':True,
    }),
    ('AV1 MKV 2160p60 4K', {
        'video_codec':'AV1', 'quality':35, 'sw_preset':'slow',
        'hw_preset':'p4', 'amf_quality':'quality', 'qsv_preset':'slow',
        'resolution':'4K (3840x2160)', 'aspect_ratio':'Source',
        'anamorphic':False, 'deinterlace':'None',
        'use_nvenc':False, 'use_qsv':False, 'use_amf':False,
        'sub_track':'None', 'sub_burn':False,
        'two_pass':False, 'target_bitrate':'10500k',
        'use_crop':False, 'crop_values':'', 'keep_chapters':True,
    }),
    ('-- Hardware --', None),
    ('H.265 NVENC 2160p 4K', {
        'video_codec':'H.265', 'quality':30, 'sw_preset':'medium',
        'hw_preset':'medium', 'amf_quality':'balanced', 'qsv_preset':'medium',
        'resolution':'4K (3840x2160)', 'aspect_ratio':'Source',
        'anamorphic':False, 'deinterlace':'None',
        'use_nvenc':True, 'use_qsv':False, 'use_amf':False,
        'sub_track':'None', 'sub_burn':False,
        'two_pass':False, 'target_bitrate':'7500k',
        'use_crop':False, 'crop_values':'', 'keep_chapters':True,
    }),
    ('H.265 NVENC 1080p', {
        'video_codec':'H.265', 'quality':27, 'sw_preset':'medium',
        'hw_preset':'medium', 'amf_quality':'balanced', 'qsv_preset':'medium',
        'resolution':'1080p (1920x1080)', 'aspect_ratio':'Source',
        'anamorphic':False, 'deinterlace':'None',
        'use_nvenc':True, 'use_qsv':False, 'use_amf':False,
        'sub_track':'None', 'sub_burn':False,
        'two_pass':False, 'target_bitrate':'4000k',
        'use_crop':False, 'crop_values':'', 'keep_chapters':True,
    }),
    ('H.265 QSV 2160p 4K', {
        'video_codec':'H.265', 'quality':28, 'sw_preset':'medium',
        'hw_preset':'p4', 'amf_quality':'speed', 'qsv_preset':'veryfast',
        'resolution':'4K (3840x2160)', 'aspect_ratio':'Source',
        'anamorphic':False, 'deinterlace':'None',
        'use_nvenc':False, 'use_qsv':True, 'use_amf':False,
        'sub_track':'None', 'sub_burn':False,
        'two_pass':False, 'target_bitrate':'7500k',
        'use_crop':False, 'crop_values':'', 'keep_chapters':True,
    }),
    ('H.265 QSV 1080p', {
        'video_codec':'H.265', 'quality':25, 'sw_preset':'medium',
        'hw_preset':'p4', 'amf_quality':'speed', 'qsv_preset':'veryfast',
        'resolution':'1080p (1920x1080)', 'aspect_ratio':'Source',
        'anamorphic':False, 'deinterlace':'None',
        'use_nvenc':False, 'use_qsv':True, 'use_amf':False,
        'sub_track':'None', 'sub_burn':False,
        'two_pass':False, 'target_bitrate':'4000k',
        'use_crop':False, 'crop_values':'', 'keep_chapters':True,
    }),
]
